lib/saltlint/rules/JinjaStatementHasSpacesRule.py, lib/saltlint/rules/JinjaVariableHasSpacesRule.py, tests/unit/TestJinjaStatementHasSpaces.py, tests/unit/TestJinjaVariableHasSpaces.py
Update name of existing `VariableHasSpacesRule` to `JinjaVariableHasSpacesRule` and add `JinjaStatementHasSpacesRule`.
=> Update Jinja rules

README.rst, tests/unit/TestSkipRule.py
Add unit test for testing skipped rules and update README.rst to include example.
=> Add unit test for testing skipped rules

setup.py
=> Bump version to v0.0.2

lib/saltlint/rules/FileModeLeadingZeroRule.py, lib/saltlint/rules/FileModeQuotationRule.py, setup.py
=> Bump version to v0.0.3

setup.py
=> Bump version to v0.0.4

README.rst
=> docs(readme): add configuration file example

setup.py
Bump version to v0.0.5 to include the changes by @myii:
- #13 
- #14 
- #15
=> Bump version to v0.0.5

lib/saltlint/rules/JinjaCommentHasSpacesRule.py, lib/saltlint/rules/JinjaStatementHasSpacesRule.py, lib/saltlint/rules/JinjaVariableHasSpacesRule.py, tests/unit/TestJinjaCommentHasSpaces.py, tests/unit/TestJinjaStatementHasSpaces.py, tests/unit/TestJinjaVariableHasSpaces.py
=> Allow '+' in Jinja variable whitespace rules

tests/unit/TestTrailingWhitespaceRule.py
=> Add unit test for trailing whitespace rule

tests/unit/TestNoTabsRule.py
=> Add test for no tabs rule

lib/saltlint/rules/YamlHasOctalValueRule.py, setup.py
=> Bump version to v0.0.6

README.rst, tox.ini
Add coverage reporting using [coveralls.io](https://coveralls.io/github/roaldnefs/salt-lint), and update the badges in the `README.rst`.
=> Add coverage reporting

saltlint/rules/JinjaPillarGrainsGetFormatRule.py, tests/unit/TestJinjaPillarGrainsGetFormatRule.py
- Trigger on faulty grains.get
- Trigger on faulty pillar.get
- UnitTests are included
Fixes #57 and #58
Signed-off-by: Jeffrey Bouter <jeffrey@kn0x.org>
=> Add checks for pillar.get and grains.get

.travis.yml, README.md, saltlint/cli.py, saltlint/config.py, tests/unit/TestConfig.py
Hi @roaldnefs,
PTAL.
Fixes #124.
=> Fix codespell issues

saltlint/cli.py, saltlint/config.py, saltlint/linter.py, tests/unit/TestConfig.py
Update `list()` to `[]` and `dict()` to `{}` for performance improvement.
Fixes #132.
=> Update list() to [] and dict() to {}

.github/workflows/actions.yml, .github/workflows/lint.yml, .markdownlint.yaml, CONTRIBUTING.md
=> Enable markdown linting

.github/workflows/lint.yml
=> Add Docker linting

README.md, saltlint/cli.py, saltlint/config.py, tests/unit/TestConfig.py
Fix spelling issues found by codespell. 
Fixes #124
=> Fix spelling issues found by codespell

saltlint/cli.py, saltlint/config.py, saltlint/linter.py
Update `list()` to `[]` and `dict()` to `{}` as a performance
improvement.
Fixes #132.
=> Update list() and dict() entries

README.md, docker/Dockerfile
- Re-work the Dockerfile to craft a minimal container
- Explain in the README how to use this container
=> Update the docker stuff

.github/workflows/actions.yml, .github/workflows/lint.yml
- Also run all checks on master branch, in order to specify proper
badges
=> Update GitHub Actions

README.md
Hi,
there's an error in the suggested configuration for `pre-commit` which I've corrected here.
=> docs: fix `pre-commit` configuration

README.md
Fix pre-commit example in `README.md`.
=> Fix pre-commit example in README.md

saltlint/__init__.py
=> Release version 0.4.0

.github/workflows/build.yml, .github/workflows/lint.yml, .github/workflows/publish-to-pypi.yml, README.md, saltlint/cli.py
=> Merge develop forward

saltlint/rules/YamlHasOctalValueRule.py, tests/unit/TestYamlHasOctalValueRule.py
Fix faulty match on MAC address for octal values.
Fixes #202
=>  Fix faulty match on MAC address for octal values

README.md, saltlint/linter/rule.py, saltlint/linter/runner.py, saltlint/rules/CmdRunQuietRule.py, saltlint/rules/CmdWaitRecommendRule.py, saltlint/rules/FileExtensionRule.py, saltlint/rules/FileModeLeadingZeroRule.py, saltlint/rules/FileModeQuotationRule.py, saltlint/rules/JinjaCommentHasSpacesRule.py, saltlint/rules/JinjaPillarGrainsGetFormatRule.py, saltlint/rules/JinjaStatementHasSpacesRule.py, saltlint/rules/JinjaVariableHasSpacesRule.py, saltlint/rules/NoTabsRule.py, saltlint/rules/SLSFileNameRule.py, saltlint/rules/YamlHasOctalValueRule.py, saltlint/utils.py, tests/__init__.py, tests/unit/TestSLSFileNameRule.py
Feat: add rule to check file name of SLS files (fixes #205)
=> Merge develop into master

.github/workflows/lint.yml, README.md, saltlint/rules/FileManagedReplaceContentRule.py, saltlint/rules/JinjaCommentHasSpacesRule.py, saltlint/rules/JinjaStatementHasSpacesRule.py, saltlint/rules/JinjaVariableHasSpacesRule.py, saltlint/rules/YamlHasOctalValueRule.py, tests/unit/TestFileManagedReplaceContentRule.py
- Check if replace: False is given when no content options are specified
on a file.managed state
- Fix description notation in several tests
Fixes #177
=> Add new file managed content rule

saltlint/rules/SLSFileNameRule.py, tests/unit/TestSLSFileNameRule.py
Only apply rule 214 on SLS files.
=> Only apply rule 214 on SLS files

.github/workflows/lint.yml, README.md, saltlint/linter/rule.py, saltlint/rules/CmdWaitRecommendRule.py, saltlint/rules/FileManagedReplaceContentRule.py, saltlint/rules/JinjaCommentHasSpacesRule.py, saltlint/rules/JinjaStatementHasSpacesRule.py, saltlint/rules/JinjaVariableHasSpacesRule.py, saltlint/rules/SLSFileNameRule.py, saltlint/rules/StateDeprecationDockerAbsent.py, saltlint/rules/StateDeprecationDockerImageAbsent.py, saltlint/rules/StateDeprecationDockerImagePresent.py, saltlint/rules/StateDeprecationDockerModWatch.py, saltlint/rules/StateDeprecationDockerNetworkAbsent.py, saltlint/rules/StateDeprecationDockerNetworkPresent.py, saltlint/rules/StateDeprecationDockerRunning.py, saltlint/rules/StateDeprecationDockerStopped.py, saltlint/rules/StateDeprecationDockerVolumeAbsent.py, saltlint/rules/StateDeprecationDockerVolumePresent.py, saltlint/rules/StateDeprecationElasticsearchIndexRule.py, saltlint/rules/StateDeprecationVirtRevertedRule.py, saltlint/rules/StateDeprecationVirtSavedRule.py, saltlint/rules/StateDeprecationVirtUnpoweredRule.py, saltlint/rules/YamlHasOctalValueRule.py, tests/unit/TestDeprecationRule.py, tests/unit/TestFileManagedReplaceContentRule.py, tests/unit/TestSLSFileNameRule.py
Merge `develop` into `main`.
Fixes #177
Fixes #204
=> Merge develop into main

saltlint/utils.py
Add `.j2` as Jinja file extension to detect Jinja files.
=> Add .j2 as Jinja file extension

.readthedocs.yml, docs/contributing.rst, saltlint/__init__.py
Bump version to `0.5.0` and update contribution guide to use the `main` branch as the base branch.
=> Bump version to 0.5.0

CHANGELOG.md, saltlint/__init__.py
=> chore: bump version to v0.5.2

CHANGELOG.md, docs/index.md, saltlint/__init__.py
Signed-off-by: Jeffrey Bouter <jb@warpnet.nl>
=> Release 0.6.1

saltlint/cli.py
Resolves #262
Resolves warpnet/SublimeLinter-salt-lint#19
=> Close temporary file after writing STDIN

.pylintrc, CHANGELOG.md, saltlint/rules/FileModeLeadingZeroRule.py, saltlint/rules/FileModeQuotationRule.py, tests/unit/TestFileModeLeadingZeroRule.py, tests/unit/TestFileModeQuotationRule.py
Ignore non file mode lines in rule 207 and 208.
Closes #255
=> Ignore non file mode lines in rule 207 and 208

.github/workflows/docker-release-edge.yml, .github/workflows/docker-release-stable.yml
Signed-off-by: Jeffrey Bouter <jb@warpnet.nl>
=> feat[docker]: Add support for ARM

.pylintrc, saltlint/config.py, saltlint/formatters/default.py, saltlint/formatters/severity.py, saltlint/linter/match.py, saltlint/rules/NoIrregularSpacesRule.py
Fix Python linting issues discovered by the new pylint version in #290.
=> fix: python linting issues

docs/index.md
Fix pre-commit configuration example in the documentation.
=> fix(docs): pre-commit configuration example

setup.py, tests/unit/TestNoIrregularSpacesRule.py
Fix pylint issues discovered in the latest GitHub action workflow runs.
=> Fix pylint issues

CHANGELOG.md
Add missing entries to the changelog.
=> Add missing entries to changelog

CHANGELOG.md, saltlint/__init__.py, saltlint/rules/YamlHasOctalValueRule.py, tests/unit/TestYamlHasOctalValueRule.py
As reported in https://github.com/warpnet/salt-lint/issues/299
=> rev(rule210): Resolve causing a lot of false positives

.github/workflows/tox.yml, CHANGELOG.md, setup.py, tox.ini
=> Add Python 3.12 support
