warpnet/salt-lint

- lib/saltlint/rules/FileModeQuotationRule.py
- tests/unit/TestFileModeQuotationRule.py
- Add a rule to check for file modes. Supports:
- mode
- file_mode
- dir_mode
Fixes #5
> Add File Mode Quotation rule

- lib/saltlint/formatters/__init__.py
in salt 2017.7 `salt.utils.color.get_colors()` was located under `salt.utils.get_colors()`.
This PR fallback to importing `salt.util` if `salt.util.color` can't be imported, making salt-lint compatible with salt 2017.7
> Make salt-lint compatible with salt 2017.7

- lib/saltlint/rules/JinjaVariableHasSpacesRule.py
- tests/unit/TestJinjaVariableHasSpaces.py
* https://jinja.palletsprojects.com/en/2.10.x/templates/#whitespace-control
- If you add a minus sign (-) to the start or end of a block
(e.g. a For tag), a comment, or a variable expression,
the whitespaces before or after that block will be removed
* Example from SaltStack-Formulas:
- https://travis-ci.org/myii/php-formula/jobs/593649688#L464-L466
- This particurlar invocation is used in numerous formulas
> fix(jinja_variables): use same base regex as Jinja statements

- lib/saltlint/rules/JinjaCommentHasSpacesRule.py
- tests/unit/TestJinjaCommentHasSpaces.py
* Related to #13
* https://jinja.palletsprojects.com/en/2.10.x/templates/#whitespace-control
- If you add a minus sign (-) to the start or end of a block
(e.g. a For tag), a comment, or a variable expression,
the whitespaces before or after that block will be removed
> feat(jinja_comments): lint in the same way as statements and variables

- README.rst
Add instructions to the `README.rst` on how to use [salt-lint](https://github.com/marketplace/actions/salt-lint) as a GitHub Action.
> Add GitHub Action instructions

- lib/saltlint/rules/YamlHasOctalValueRule.py
- tests/unit/TestYamlHasOctalValueRule.py
Add rule (`YamlHasOctalValueRule`) to check on unquoted octal values.  When using a numeric value that includes a leading zero you must wrap the value in quotes. If the value is not wrapped in quotes it will be read by YAML as an integer and evaluated as an octal.
Fixes #29.
> Add YamlHasOctalValueRule

- lib/saltlint/rules/YamlHasOctalValueRule.py
- tests/unit/TestYamlHasOctalValueRule.py
Fix `YamlHasOctalValueRule` to only trigger after `: ` entries. Otherwise `example010` would also trigger.
Fixes #34.
> Fix YamlHasOctalValueRule

- lib/saltlint/rules/YamlHasOctalValueRule.py
- tests/unit/TestYamlHasOctalValueRule.py
Yaml also interpret any sequence of zeros (i.e. 00, 000, 0000, etc.) as an octal value.
For more information see: https://github.com/roaldnefs/salt-lint/pull/31#issuecomment-538950630.
> Fix octal values

- lib/saltlint/__init__.py
- lib/saltlint/__main__.py
- setup.py
Remove `six` and` pyyaml` as dependency, because they are already installed by `salt`.
Fixes the following error message during install of salt-lint:
> ERROR: salt 2019.2.1 has requirement PyYAML<5.1, but you'll have pyyaml 5.1.2 which is incompatible.
> Remove six and pyyaml as dependency

- README.rst
- lib/saltlint/__main__.py
Port option to list all tags from ansible-lint to salt-lint. Required method `RulesCollection.listtags()` was already in place.
> Add option to list all tags

- README.rst
- lib/saltlint/__main__.py
Hope this PR solves the issue.
Fixes #45.
> Feature Request: allow users to build their own set of rules

- CONTRIBUTING.md
Update `CONTRIBITING.md` to use `develop` branch and add instructions to base new branches on the `upstream` repository.
This pull request process is a simplified version of [SaltStack's own guide](https://docs.saltstack.com/en/latest/topics/development/contributing.html#sending-a-github-pull-request).
> Update CONTRIBITING.md to use develop branch

- lib/saltlint/__init__.py
Add option to run rules that use the full (raw) text of the input file instead of line by line.
Example rule:
```python
class TestRule(SaltLintRule):
id = '999'
shortdesc = 'Example rule that receives the full text'
description = 'Example rule that receives the full text of the state'
severity = 'LOW'
tags = ['example']
version_added = 'develop'
def matchtext(self, file, text):
results = []
results.append((999, 'section', self.shortdesc))
return results
```
Result in the following output:
```
[999] Example rule that receives the full text
tests/test-extension-success.sls:999
section
```
This is especially useful after implementing #52, because users could now implement rules that use the full raw text.
> Add option to run rules that use the full text

- saltlint/cli.py
- saltlint/config.py
- saltlint/linter.py
- saltlint/utils.py
- setup.py
- tests/__init__.py
- tests/unit/TestConfig.py
- tests/unit/TestFileExtension.py
- tests/unit/TestRunner.py
Add configuration option to ignore rules per file, e.g.:
```yaml
---
rules:
formatting:
ignore: |
first.sls
second.sls
210:
ignore: |
state/*.sls
*.jinja
```
This PR also moves configuration parsing from `cli.py` to `config.py`. This makes `cli.py` less complex and allows the program to only pass the config object instead of having to pass the updated options.
Fixes #48.
> Add config option to ingore rules per file

- saltlint/rules/YamlHasOctalValueRule.py
- tests/unit/TestYamlHasOctalValueRule.py
Fix rule 210 to skip unquoted non-number values (e.g. `000-default`) as they aren't octal values but strings.
This commit also allows optional whitespace around the unquoted octal value, and the value followed by a YAML or JINJA comment (e.g. `0700 {# JINJA COMMENT #}`).
Fixes #68.
> Fix 210 to skip non-number values

- saltlint/__init__.py
- saltlint/rules/JinjaCommentHasSpacesRule.py
- saltlint/rules/JinjaPillarGrainsGetFormatRule.py
- saltlint/rules/JinjaStatementHasSpacesRule.py
- saltlint/rules/JinjaVariableHasSpacesRule.py
Version `v0.0.10` release, requires to be tagged after being merged into `master`.
- Add rule `211` to check for faulty usage of `grains.get` or `pillar.get` (#60).
- Add configuration option to ignore rules per file (#67).
- Changed author to Warpnet B.V. (#61).
- Change `README` to Markdown format (#65).
- Refactor the way the configuration is parsed (#67).
- Group Jinja rules under the tag `jinja` (332413d).
- Fix rule `210` to skip non-number values (#69). 
Closes #48, #57, #58, #61, #64, #68.
>  Version 0.0.10 Release

- saltlint/cli.py
This PR fixes UTF-8 encoding under python2 when salt-lint is piped to another program.
This fixes  #74
> Fix utf-8 encoding

- saltlint/rules/NoIrregularSpacesRule.py
- tests/unit/TestNoIrregularSpacesRule.py
This PR adds a rule to check if state contains irregular spaces as discussed under #74.
Irregular spaces are usually unneeded and unwanted.
List taken from similar [ESLint](https://eslint.org/docs/rules/no-irregular-whitespace) rule.
> Add rule to check for irregular spaces

- README.md
- Add a table with all rules, linking to corresponding wiki entries
> Update README.md to include list of rules

- saltlint/cli.py
Fixes #79.
```bash
$ python -m saltlint < init.sls
```
Some caveats:
- This implementation doesn't use a context manager. The temporary file will outlive script execution if intermediate code raises an exception.
- Linter output includes the (arbitrary, useless) path of the temporary file.
> Read input from stdin

- saltlint/cli.py
Fix encoding to use utf-8 by default in Python 2, the default encoding in Python 3 is already utf-8. This fix will wrap `sys.stdout` in a object that automatically encodes an unicode string into utf-8, in Python 2 only.
An alternative to this would be to set the `PYTHONIOENCODING='utf-8'` environment variable before running `salt-lint`, but this would require an extra action on the user side.
The old solution using `str.encode('utf-8')` caused byte string (e.g. `b''`) output in Python 3...
Fixes #74.
> Fix encoding to use utf-8

- README.md
- saltlint/cli.py
- saltlint/config.py
- saltlint/formatters/__init__.py
Add JSON formatter to make it easier to interpret the output of `salt-lint`. When using the `--json` flag the output will be similar to:
```json
[{
"id": "205",
"message": "Use \".sls\" as a Salt State file extension",
"filename": "tests/test-extension-failure",
"linenumber": 1,
"line": "tempfile:",
"severity": "MEDIUM"
}, {
"id": "212",
"message": "Most files should not contain irregular spaces",
"filename": "tests/test-extension-failure",
"linenumber": 3,
"line": "    - test:\u00a0test",
"severity": "LOW"
}]
```
Fixes #80.
> Add JSON Formatter

- saltlint/formatters/__init__.py
Fix format string to also use square brackets with the `--nocolor` option.
Fixes #86.
> Fix format string to use square brackets

- LICENSE
- docker/Dockerfile
- saltlint/__init__.py
- saltlint/rules/NoIrregularSpacesRule.py
Version `v0.1.0` release, requires to be tagged after being merged into `master`.
- Add rule `212` to check for irregular spaces (#76).
- Add initial `Dockerfile` for `salt-lint` (#77).
- Add option to output in JSON format (#80).
- Add option to read from standard input (#79).
- Add overview of all rules in `README.md` (#82).
- Fix output encoding when using Python 2 (#74).
- Fix format string to use square brackets with the `--nocolor` option (#86).
> Version 0.1.0 Release

- saltlint/linter.py
Fix typos in `saltlint/linter.py`, as pointed out by @hbokh in https://github.com/warpnet/salt-lint/issues/100#issuecomment-552614281.
> Fix typos in saltlint/linter.py

- saltlint/cli.py
- Add support for `--nocolour` and `--force-colour`
Fixes #89
> Update CLI options to support British English

- README.md
- saltlint/cli.py
- saltlint/config.py
- saltlint/formatters/__init__.py
I added this as an argument that defaults to off so that the output stays consistent for people. If you want it, the flag is `--add-severity`.
> Add severity to standard output. Fixes #93

- .pylintrc
- .travis.yml
- saltlint/cli.py
- saltlint/config.py
- saltlint/formatters/__init__.py
- saltlint/linter.py
- saltlint/rules/FileExtensionRule.py
- saltlint/rules/FileModeLeadingZeroRule.py
- saltlint/rules/FileModeQuotationRule.py
- saltlint/rules/JinjaCommentHasSpacesRule.py
- saltlint/rules/JinjaPillarGrainsGetFormatRule.py
- saltlint/rules/JinjaStatementHasSpacesRule.py
- saltlint/rules/JinjaVariableHasSpacesRule.py
- saltlint/rules/LineTooLongRule.py
- saltlint/rules/NoIrregularSpacesRule.py
- saltlint/rules/NoTabsRule.py
- saltlint/rules/TrailingWhitespaceRule.py
- saltlint/rules/YamlHasOctalValueRule.py
- tests/__init__.py
Hi @roaldnefs,
I fixed here 2 pylint issues: **unused-argument**, and **dangerous-default-value**.
This also move the configuration to a separated .pylintrc file, so that the configuration has much more flexibility. Let me know if you agree with that. 
Pylint wants normally the snake_case instead of the CamelCase you are using here. Do we want to stay with this style?
> Fix some more pylint

- saltlint/cli.py
- saltlint/config.py
- saltlint/linter.py
Change the exclude path(s) option and configuration to use pathspec. This allows the paths to be matched on Git's wildmatch pattern. Git uses wildmatch for its [gitignore](http://git-scm.com/docs/gitignore) files.
Fixes #100.
> Change exclude path(s) to use pathspec

- tests/unit/TestConfig.py
Fix configuration test after introducing pathspec in #126. It is causing the unit tests on the `develop` branch to break.
> Fix configuration test after introducing pathspec

- .pylintrc
- README.md
- saltlint/cli.py
- saltlint/config.py
Change `optparse` to `argparse`, because `optparse` is [deprecated since Python 2.7](https://docs.python.org/2/library/optparse.html).
Fixes #128.
> Change optparse to argparse

- .travis.yml
Remove Travis deploy condition in `.travis.yml` because the deploy condition is already specified in the deploy job configuration.
Fixes #122
> Fix automated PyPi deployment in Travis configuration

- saltlint/rules/JinjaPillarGrainsGetFormatRule.py
- tests/unit/TestJinjaPillarGrainsGetFormatRule.py
Fix rule `211`. The rule should have spotted the usage of `pillar.get['key']` or `grains.get['key']`. All example on the [wiki](https://github.com/warpnet/salt-lint/wiki/211) are actually correct examples and will be rendered in Jinja without any problems.
Using `pillar.get['key']` in a SLS file results in:
```
local:
Data failed to compile:
----------
Rendering SLS 'base:example' failed: Jinja variable 'method object' has no attribute ‘key'
```
Using `grains.get['key']` results in:
```
local:
Data failed to compile:
----------
Rendering SLS 'base:example' failed: Jinja variable 'builtin_function_or_method object' has no attribute 'key'
```
Fixes #140
> Fix rule 211

- saltlint/__init__.py
- saltlint/rules/JinjaPillarGrainsGetFormatRule.py
- tests/unit/TestJinjaPillarGrainsGetFormatRule.py
Version `v0.2.1` release, requires to be tagged after being merged into `master` and  the [wiki](https://github.com/warpnet/salt-lint/wiki/211) needs to be updated.
- Fix rule 211 (#142, cherry picked from `develop`).
Fixes #140.
> Version 0.2.1 Release

- saltlint/__init__.py
Bump version to `v0.2.2`.
Releasing the 0.2.2 version also fixes #145.
> Bump version to v0.2.2

- saltlint/config.py
- saltlint/formatters/__init__.py
- saltlint/linter.py
- setup.py
Remove Salt as a dependency of salt-lint by:
- including the `six` and `pyyaml` libraries directly.
- specifying the colors directly.
This also fixes #135.
> Remove Salt as a dependency

- saltlint/__init__.py
- saltlint/cli.py
- saltlint/config.py
- saltlint/formatters/__init__.py
- saltlint/linter.py
- setup.py
Version `v0.3.0` release, requires to be tagged after being merged into `master`.
- Remove Salt as a dependency (#147, cherry picked from `develop`).
Fixes #135.
> Version 0.3.0 Release

- docker/Dockerfile
Fix Dockerfile for salt-lint for version 0.3.0 by removing the version
pinning and only install salt-lint itself as SaltStack has been removed
as dependency.
> Fix Dockerfile for salt-lint for version 0.3.0

- CODE_OF_CONDUCT.md
Add intial code of conduct to the project based upon the GitHub [Contributor Covenant Code of Conduct](https://github.com/warpnet/salt-lint/community/code-of-conduct/new?template=contributor-covenant) template.
> Add Code of Conduct to the project

- .github/workflows/publish-to-pypi.yml
Automatically build and publish salt-lint to PyPi using GitHub Actions.
Fixes #122
> Automate PyPi release using GitHub Actions

- .github/workflows/publish-to-pypi.yml
Only publish build on tags to prevent duplicate releases.
> Only publish build on tags to prevent duplicate releases

- .github/workflows/publish-to-pypi.yml
Fix GitHub Actions to only release to PyPi on tagged commits in the master branch.
> Fix GitHub Actions automated release to PyPi

- .github/workflows/lint.yml
- README.md
- saltlint/cli.py
Replace `optparse` by `argparse` and update `README.md` to show the new usage information.
The arguments are backwards compatible with the previous version of `salt-lint`.
Fixes #128
> Replace optparse by argparse

- README.md
- saltlint/cli.py
Add `--version` flag to the command line interface of salt-lint.
Closes #185
> Add --version flag to CLI

- .github/workflows/build.yml
- .github/workflows/lint.yml
- .github/workflows/publish-to-pypi.yml
- README.md
Rename the `master` branch to `main`.
Fixes #186
> Rename master branch to main

- saltlint/linter.py
- saltlint/rules/JinjaVariableHasSpacesRule.py
- tests/unit/TestJinjaVariableHasSpaces.py
This pull request fixes #192 by allowing certain combinations of doubly curl braces to exist without post or pre brace spaces. This is to allow string formatting strings such as `"{{0}}"` to exist within Jinja statements.
I think this covers enough of the use-case to be useful. We're linting and not syntax checking so I think this should be suitable.
I have included an increased amount of testing around the brace spaces rule as well.
> Support doubly braced string format

- saltlint/__main__.py
- saltlint/config.py
- setup.py
Add exception chaining and embedded tracebacks by using the raise from
statement.
For more information see: https://legacy.python.org/dev/peps/pep-3134/
> Fix pylint errors by using raise from statement

- saltlint/cli.py
Allow salt-lint to only use STDIN by making the files argument optional.
Fixes #193
> Make files argument optional to allow STDIN

- saltlint/__init__.py
Bump version to `v0.4.2`. This pull request is work in progress until #195 and #194 have been merged into `develop`. 
- Allow STDIN to be used as the only input (#194)
- Support doubly braced string format in Jinja statement (#196)
> Bump version to v0.4.2

- README.md
- saltlint/rules/CmdRunQuietRule.py
- saltlint/utils.py
- tests/unit/TestCmdRunQuietRule.py
- Warn on using the quiet argument with cmd.run
- Fixes #40
> Warn on using quiet with cmd.run

- README.md
- saltlint/linter/rule.py
- saltlint/linter/runner.py
- saltlint/rules/CmdRunQuietRule.py
- saltlint/rules/CmdWaitRecommendRule.py
- saltlint/rules/FileExtensionRule.py
- saltlint/rules/FileModeLeadingZeroRule.py
- saltlint/rules/FileModeQuotationRule.py
- saltlint/rules/JinjaCommentHasSpacesRule.py
- saltlint/rules/JinjaPillarGrainsGetFormatRule.py
- saltlint/rules/JinjaStatementHasSpacesRule.py
- saltlint/rules/JinjaVariableHasSpacesRule.py
- saltlint/rules/NoTabsRule.py
- saltlint/rules/SLSFileNameRule.py
- saltlint/rules/YamlHasOctalValueRule.py
- saltlint/utils.py
- tests/__init__.py
- tests/unit/TestSLSFileNameRule.py
Add new rule to check file name of SLS files, as SLS file with a period
in the name (besides the suffix period) can not be referenced.
This pull request also allows rules to only run for specific file types by
adding valid `languages` to the rule. File types are determined based
upon the file extension.
Fixes #205
> Add rule to check file name of SLS files

- saltlint/linter/rule.py
- saltlint/rules/CmdWaitRecommendRule.py
- saltlint/rules/StateDeprecationDockerAbsent.py
- saltlint/rules/StateDeprecationDockerImageAbsent.py
- saltlint/rules/StateDeprecationDockerImagePresent.py
- saltlint/rules/StateDeprecationDockerModWatch.py
- saltlint/rules/StateDeprecationDockerNetworkAbsent.py
- saltlint/rules/StateDeprecationDockerNetworkPresent.py
- saltlint/rules/StateDeprecationDockerRunning.py
- saltlint/rules/StateDeprecationDockerStopped.py
- saltlint/rules/StateDeprecationDockerVolumeAbsent.py
- saltlint/rules/StateDeprecationDockerVolumePresent.py
- saltlint/rules/StateDeprecationElasticsearchIndexRule.py
- saltlint/rules/StateDeprecationVirtRevertedRule.py
- saltlint/rules/StateDeprecationVirtSavedRule.py
- saltlint/rules/StateDeprecationVirtUnpoweredRule.py
- tests/unit/TestDeprecationRule.py
- Add DeprecationRule function
- Add new deprecation rules
- ~Unit tests still need to be written~
Fixes #204
> Add new deprecation functionality

- README.md
Salt-lint support has just been added in ale vim plugin and I want to reflect that on salt-lint documentation.
> Add link to dense-analysis/ale vim plugin in README

- CHANGELOG.md
- setup.py
Add `CHANGELOG.md` to list all notable changes for each new version. The `CHANGELOG.md` will also be appended to the `long_description` of the Python package.
> Add CHANGELOG.md

- CHANGELOG.md
- saltlint/linter/runner.py
- tests/unit/TestRunner.py
Ensure all the excluded paths provided in the configuration and/or via
the CLI are passed to the runner.
Fixes #230
> fix: ensure all excluded paths are included

- README.md
Fix the license badge in the `README.md` file, as GitHub isn't able to detect the license of the project because multiple license files are found.
> fix: set license badge in README.md

- CHANGELOG.md
- README.md
- saltlint/__init__.py
Bump version to **0.5.1** and update the `CHANGELOG.md` file accordingly.
**Note:** create a new release after merging this PR.
> chore: bump version to 0.5.1

- CHANGELOG.md
- MANIFEST.in
- setup.py
Append the contents of the `CHANGELOG.md` file to the long description of the package instead of the duplicate `README.md` contents.
> fix: append changelog to long description in setup.py

- CHANGELOG.md
- saltlint/linter/rule.py
- saltlint/rules/JinjaCommentHasSpacesRule.py
- saltlint/rules/JinjaPillarGrainsGetFormatRule.py
- saltlint/rules/JinjaStatementHasSpacesRule.py
- saltlint/rules/JinjaVariableHasSpacesRule.py
- tests/unit/TestJinjaCommentHasSpaces.py
- tests/unit/TestJinjaStatementHasSpaces.py
- tests/unit/TestJinjaVariableHasSpaces.py
Ignore Jinja specific rules in Jinja escaped blocks.
Fixes #201
> fix: ignore Jinja rules in Jinja escaped blocks

- .github/workflows/tox.yml
- saltlint/config.py
- saltlint/linter/rule.py
- tox.ini
After dropping the Python 2.7 support in #239, Python type hint can be used. This PR will add a mypy type hint test using tox and fixes all required type hint to allow the new test to pass.
> test: add type hint test using mypy

- saltlint/cli.py
- saltlint/utils.py
- tests/unit/TestConfig.py
Replace `imp` by `importlib` in `saltlint/utils.py` as `imp` has been deprecated and ignore all `consider-using-with` errors.
> Replace imp by importlib

- CHANGELOG.md
- saltlint/linter/rule.py
- saltlint/rules/TypoContentsRule.py
- saltlint/rules/TypoOnchangesRule.py
- saltlint/rules/TypoRequireRule.py
- setup.py
- tests/unit/TestTypoContentsRule.py
- tests/unit/TestTypoOnchangesRule.py
- tests/unit/TestTypoRequireRule.py
As Salt is unable to catch some frequent typos there are few checks:
- "onchange" (must be "onchanges")
- "requires" (must be "require")
- "content" (must be "contents")
> feat: add frequent typo-catching rules

- CHANGELOG.md
- docs/index.md
- saltlint/__init__.py
- saltlint/rules/TypoContentsRule.py
- saltlint/rules/TypoOnchangesRule.py
- saltlint/rules/TypoRequireRule.py
Version 0.6.0 release.
- Drop Python 2.7 support ([#239](https://github.com/warpnet/salt-lint/pull/239)).
- Rule 216, 217 and 218 for catching common typographical errors ([#249](https://github.com/warpnet/salt-lint/pull/249)).
> chore: bump version to v0.6.0

- .pre-commit-config.yaml
- tox.ini
Version bump pre-commit repos to allow Github Actions to successfully lint the files in the `tests` workflow.
> Version bump pre-commit repos

- docs/rules/formatting.md
I was confused for a while trying to figure out why the same syntax was both correct and incorrect.
> docs: 211: Fix an inconsistency in pillar.get formatting

- CHANGELOG.md
- saltlint/rules/JinjaVariableHasSpacesRule.py
- tests/unit/TestJinjaVariableHasSpaces.py
Fix false positive when detecting missing spaces in the Jinja variable when the Jinja statement is nested in literal braces.
Closes #257
> Fix false positive for spaces in Jinja variable

- CHANGELOG.md
- docs/rules/formatting.md
- docs/rules/index.md
- saltlint/rules/NestedDictRule.py
- tests/unit/TestNestedDictRule.py
This pull request add a check on proper nested dictionary over-indentation as advised in https://docs.saltproject.io/en/latest/topics/troubleshooting/yaml_idiosyncrasies.html#nested-dictionaries
It adds Rule 219 (which seems to be the first never-used 2xx rule number). Feel free to change rule number if needed.
This fixes #282
> feat: Add nested dictionary formating check

- saltlint/rules/TypoOnchangesRule.py
- tests/unit/TestTypoOnchangesRule.py
Add to the existing rule to catch `onchanges` typos:
```
on_change:
on_change_any:
on_change_in:
on_changes:
on_changes_any:
on_changes_in:
```
> [FEATURE] Add regex for alternate typo of onchanges

- .github/workflows/tox.yml
- .pre-commit-config.yaml
Fix the GitHub workflow run for running tox by:
- Set platform version to Ubuntu 20.04 for running tox in the GitHub workflows as there is no Python 3.6 available on latest Ubuntu version, for more information see: https://github.com/actions/setup-python/issues/544#issuecomment-1320295576.
- Update Flake8 to be able to run on all Python versions.
> Fix GitHub workflow for running tox

- README.md
Fix test status badge in `README.md` due to breaking change in shields.io. For more information see https://github.com/badges/shields/issues/8671.
> Fix test status badge in README.md

- .github/workflows/tox.yml
- .pre-commit-config.yaml
- CHANGELOG.md
- setup.py
- tox.ini
> feat: add python 3.11 support

- saltlint/rules/YamlHasOctalValueRule.py
- tests/unit/TestYamlHasOctalValueRule.py
Time values such as this:
```
some_calendar_entry:
file.managed:
- name: /tmp/my_unit_file
- contents: |
OnCalendar=Sun 18:00
```
should not trigger this rule.
Changed the regex to accommodate this case while still catching/ignoring previous identified test cases
> fix: octal rule triggers on time format

- setup.py
Should fix https://github.com/warpnet/salt-lint/issues/304
> Ensure python_requires adheres to pep440

- docs/man/salt-lint.1
This PR fixes the typo `saltlint` to `salt-lint` in the manpage.  It also mentions the file type for the `.salt-lint` file.
> Issue fix 311 - Documentation inconsistency

- CHANGELOG.md
- docs/index.md
- saltlint/config.py
This change will lookup for a `.salt-lint` configuration in the parent folder if no configuration is present in the current folder. It will stop going to upper level if reach the git repository root.
Which is useful if you have sub formulas, but only have the `.salt-lint` config in the repository root. 
This change is inspired by ansible-lint.
> Lookup for configuration in parent folder.

- Dockerfile
Fix install of salt-lint in Dockerfile after the project changed from `setup.py` to `pyproject.yoml`.
> fix: install of salt-lint in Dockerfile
